-- MySQL Script generated by MySQL Workbench
-- 09/02/17 17:41:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema DB3087534
-- -----------------------------------------------------
USE `DB3087534` ;

-- -----------------------------------------------------
-- Table `gg_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_User` ;

CREATE TABLE IF NOT EXISTS `gg_User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Login_Name` VARCHAR(45) NOT NULL,
  `Pwd_Hash` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Zip_Code` VARCHAR(255) NOT NULL,
  `Fon` VARCHAR(255) NULL,
  `Adress` VARCHAR(255) NULL,
  `Picture` VARCHAR(255) NULL,
  `Visibility_Flags` VARCHAR(255) NULL DEFAULT 'EMAIL:0-FON:0-ADRESS:0-PICTURE:0',
  UNIQUE INDEX `Login_Name_UNIQUE` (`Login_Name` ASC),
  PRIMARY KEY (`User_ID`),
  INDEX `Login_Name_IND` (`Login_Name` ASC),
  INDEX `Email_IND` (`Email` ASC),
  INDEX `Zip_Code_IND` (`Zip_Code` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Present`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Present` ;

CREATE TABLE IF NOT EXISTS `gg_Present` (
  `Present_ID` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(32000) NOT NULL,
  `State` VARCHAR(255) NOT NULL DEFAULT 'Vorhanden',
  `Available_until` DATETIME NULL,
  PRIMARY KEY (`Present_ID`),
  FULLTEXT INDEX `Description_TXT` (`Description` ASC),
  INDEX `Title_IND` (`Title` ASC),
  INDEX `Available_until_IND` (`Available_until` ASC),
  INDEX `State_IND` (`State` ASC),
  FULLTEXT INDEX `Title_TXT` (`Title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Demand` ;

CREATE TABLE IF NOT EXISTS `gg_Demand` (
  `User_ID` INT NOT NULL,
  `Present_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Present_ID`),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_USER_DEMAND`
    FOREIGN KEY (`User_ID`)
    REFERENCES `gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DEMAND_PRESENT`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `gg_Present` (`Present_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Offer` ;

CREATE TABLE IF NOT EXISTS `gg_Offer` (
  `User_ID` INT NOT NULL,
  `Present_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Present_ID`),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_USER_OFFER`
    FOREIGN KEY (`User_ID`)
    REFERENCES `gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OFFER_PRESENT`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `gg_Present` (`Present_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Tag` ;

CREATE TABLE IF NOT EXISTS `gg_Tag` (
  `Tag_ID` INT NOT NULL AUTO_INCREMENT,
  `Tag` VARCHAR(255) NOT NULL,
  INDEX `Tag_ID_IND` (`Tag_ID` ASC),
  PRIMARY KEY (`Tag_ID`),
  FULLTEXT INDEX `Tag_IND` (`Tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Present_has_Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Present_has_Tags` ;

CREATE TABLE IF NOT EXISTS `gg_Present_has_Tags` (
  `Present_ID` INT NOT NULL,
  `Tag_ID` INT NOT NULL,
  PRIMARY KEY (`Present_ID`, `Tag_ID`),
  INDEX `FK_Present_has_Tags_Tag_ID_IND` (`Tag_ID` ASC),
  INDEX `FK_Present_has_Tags_Present_ID_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_Present_has_Tags_Present`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `gg_Present` (`Present_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Present_has_Tags_Tag`
    FOREIGN KEY (`Tag_ID`)
    REFERENCES `gg_Tag` (`Tag_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


